services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3003
    ports:
      - 3003:3003
    environment:
      DB_HOST: tera-cluster-instance-1.clas6e6iiazg.eu-north-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_USER: tera
      DB_PASSWORD: EnsaEpt18
      DB_NAME: teradatabase
    restart: always
